<a href="https://colab.research.google.com/github/ac5589/Pytorch-tutorial-Youtube/blob/main/Intro_to_pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Introduction to pytorch

# What is a tensor:

import torch

In [3]:
data = [[1, 2, 3], [4, 5, 6]]
my_tensor = torch.tensor(data)
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
# Create desired shape
shape = (2, 3)

random = torch.randn(shape)
print(random)

tensor([[ 0.2532, -0.8366,  0.4745],
        [-1.4336,  0.1842,  0.5505]])


In [5]:
# Create by mimicking another tensor

template = torch.tensor([[1, 2], [3, 4]])

rand_like = torch.randn_like(template, dtype=torch.float)
print(rand_like)

tensor([[ 2.1438,  1.5051],
        [ 2.0504, -0.9108]])


In [6]:
# Every tensor has three atributes
tensor = torch.randn(2, 3)
print(f'Shape: {tensor.shape}')
print(f'Datatype: {tensor.dtype}')
print(f'Device: {tensor.device}')

Shape: torch.Size([2, 3])
Datatype: torch.float32
Device: cpu


In [7]:
# Automatic differntiation aka auto grad

x_data = torch.tensor([[1., 2,], [3., 4.]])

w = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)

print(f'x_data = {x_data.requires_grad}')
print(f'w = {w.requires_grad}')

x_data = False
w = True


In [8]:
# Goal: compute Z = x*y, where y = a + b

a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

y = a + b

z = x * y

print(f'grad_fn for z = {z.grad_fn}')
print(f'grad_fn for y = {y.grad_fn}')
print(f'grad_fn for a = {a.grad_fn}')

grad_fn for z = <MulBackward0 object at 0x7dfd5b5c08b0>
grad_fn for y = <AddBackward0 object at 0x7dfd5b6d92d0>
grad_fn for a = None


In [9]:
# Element wise multiplication

a = torch.tensor([[1, 2], [3 , 4]])
b = torch.tensor([[10, 20], [30 , 40]])

a *b


tensor([[ 10,  40],
        [ 90, 160]])

In [10]:
# Matrix Multiplication
a@b

tensor([[ 70, 100],
        [150, 220]])

In [11]:
# Reduction operation

scores = torch.tensor([[10., 20., 30.], [5., 10., 15.]])
scores.mean()
scores.mean(dim=1)
scores.mean(dim=0)

tensor([ 7.5000, 15.0000, 22.5000])

In [12]:
# data selection

x =torch.arange(12).reshape(3, 4)

col_2 = x[:, 2]
print(f'{col_2}')

tensor([ 2,  6, 10])


In [13]:
scores = torch.tensor([[10, 20, 30], [40, 50, 60]])
best_indices = torch.argmax(scores, dim = 0)
print(f'{best_indices} for dim = 0')
best_indices = torch.argmax(scores, dim = 1)
print(f'{best_indices} for dim = 1')

tensor([1, 1, 1]) for dim = 0
tensor([2, 2]) for dim = 1


In [14]:
data = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(data)

indices_to_select = torch.tensor([[2], [0], [3]])

selected_values = torch.gather(data, dim=1, index=indices_to_select)

print(selected_values)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 3],
        [ 5],
        [12]])


In [15]:
# Building a model from scratch

# Model: simple linear regression
# y = xW + b
def model(X, W, b):
  return X @ W + b

# first, create a fake data

# Number of data points in the input data
N = 10

# Each data point has 1 input feature and 1 output value
D_in = 1;
D_out = 1;

# Create our input data
X = torch.randn(N, D_in)

true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y_true = model(X, true_W, true_b) + torch.randn(N, D_out) * 0.1

# Initialize our parameters with random values
W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Print the weights
print(f'Initial Weight W = \n{W}\n')
print(f'Initial Bias b = \n{b}\n')

print(model(X, W, b))

# Root mean squared error
loss = ((model(X, W, b) - y_true)**2).mean()
print(loss)

# Learning the weight and bias to reduce the error
loss.backward()

# Gradients are stored in the .grad attribute
print(f'Gradient for W: \n {W.grad}\n')
print(f'Gradient for b: \n {b.grad}\n')


Initial Weight W = 
tensor([[-1.0529]], requires_grad=True)

Initial Bias b = 
tensor([-0.4140], requires_grad=True)

tensor([[-0.8500],
        [-0.7405],
        [-0.3865],
        [-0.1791],
        [ 0.9019],
        [ 0.1814],
        [-0.5863],
        [-0.7282],
        [ 0.8325],
        [ 1.1370]], grad_fn=<AddBackward0>)
tensor(4.3293, grad_fn=<MeanBackward0>)
Gradient for W: 
 tensor([[-2.5243]])

Gradient for b: 
 tensor([-0.7365])



In [16]:
# Train the model via manually update the layers

# Learning rate and epoch
lr, epochs = 0.01, 1000

# Initialize the parameters
W, b = torch.randn(1, 1, requires_grad=True), torch.randn(1, requires_grad=True)

# Iterate the weights and bias via a for loop

for epoch in range(epochs):

  # Get the prediction
  # forward Pass
  y_hat = X @ W + b

  # Get the Loss function
  loss = torch.mean(((y_hat - y_true)**2))

  # Backward Pass
  loss.backward()

  # Update the parameters
  with torch.no_grad():
    W -= lr*W.grad
    b -= lr*b.grad

  # Initialize the gradient to zero
  W.grad.zero_(); b.grad.zero_()

  if epoch%10 == 0:
    print(f'Epoch = {epoch}, W = {W.item():.3f}, b = {b.item():.3f}, Loss = {loss.item():.3f}')

print(f'True parameters, W = {true_W.item():.3f}, b = {true_b.item():.3f}')
print(f'Final learned parameters, W = {W.item()}, b = {b.item()}')



Epoch = 0, W = 0.138, b = 0.833, Loss = 1.794
Epoch = 10, W = 0.326, b = 0.755, Loss = 1.369
Epoch = 20, W = 0.488, b = 0.703, Loss = 1.070
Epoch = 30, W = 0.629, b = 0.670, Loss = 0.854
Epoch = 40, W = 0.753, b = 0.652, Loss = 0.694
Epoch = 50, W = 0.862, b = 0.644, Loss = 0.573
Epoch = 60, W = 0.958, b = 0.645, Loss = 0.477
Epoch = 70, W = 1.044, b = 0.651, Loss = 0.402
Epoch = 80, W = 1.121, b = 0.662, Loss = 0.340
Epoch = 90, W = 1.191, b = 0.675, Loss = 0.290
Epoch = 100, W = 1.253, b = 0.690, Loss = 0.248
Epoch = 110, W = 1.309, b = 0.706, Loss = 0.213
Epoch = 120, W = 1.361, b = 0.723, Loss = 0.184
Epoch = 130, W = 1.407, b = 0.740, Loss = 0.159
Epoch = 140, W = 1.450, b = 0.757, Loss = 0.138
Epoch = 150, W = 1.489, b = 0.773, Loss = 0.120
Epoch = 160, W = 1.525, b = 0.789, Loss = 0.104
Epoch = 170, W = 1.557, b = 0.804, Loss = 0.091
Epoch = 180, W = 1.587, b = 0.818, Loss = 0.080
Epoch = 190, W = 1.615, b = 0.832, Loss = 0.070
Epoch = 200, W = 1.640, b = 0.844, Loss = 0.062
Epo

In [ ]:
# Train the model via torch.nn model

# Input as one feature
# Dimension of the input = 1
D_in = 1

# Output as one value
# dimension of the output = 1
D_out = 1

# Create the Linear layer
Linear_layer = torch.nn.Linear(in_features=D_in, out_features=D_out)

print(f'Layers Weight (W) {Linear_layer.weight}')
print(f'Layers Bias (b) {Linear_layer.bias}')

# Forward Pass
y_hat_nn = Linear_layer(X)

print(f'Ouput of nn.Linear {y_hat_nn}')