<a href="https://colab.research.google.com/github/ac5589/Pytorch-tutorial-Youtube/blob/main/Intro_to_pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Introduction to pytorch

# What is a tensor:

import torch

In [3]:
data = [[1, 2, 3], [4, 5, 6]]
my_tensor = torch.tensor(data)
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
# Create desired shape
shape = (2, 3)

random = torch.randn(shape)
print(random)

tensor([[-0.9298,  0.2604, -0.4944],
        [-0.3921, -0.0351,  0.7904]])


In [8]:
# Create by mimicking another tensor

template = torch.tensor([[1, 2], [3, 4]])

rand_like = torch.randn_like(template, dtype=torch.float)
print(rand_like)

tensor([[ 0.1109, -1.0386],
        [ 0.6565,  1.1613]])


In [9]:
# Every tensor has three atributes
tensor = torch.randn(2, 3)
print(f'Shape: {tensor.shape}')
print(f'Datatype: {tensor.dtype}')
print(f'Device: {tensor.device}')

Shape: torch.Size([2, 3])
Datatype: torch.float32
Device: cpu


In [13]:
# Automatic differntiation aka auto grad

x_data = torch.tensor([[1., 2,], [3., 4.]])

w = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)

print(f'x_data = {x_data.requires_grad}')
print(f'w = {w.requires_grad}')

x_data = False
w = True


In [18]:
# Goal: compute Z = x*y, where y = a + b

a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

y = a + b

z = x * y

print(f'grad_fn for z = {z.grad_fn}')
print(f'grad_fn for y = {y.grad_fn}')
print(f'grad_fn for a = {a.grad_fn}')

grad_fn for z = <MulBackward0 object at 0x79ada973e950>
grad_fn for y = <AddBackward0 object at 0x79ada973ca00>
grad_fn for a = None


In [19]:
# Element wise multiplication

a = torch.tensor([[1, 2], [3 , 4]])
b = torch.tensor([[10, 20], [30 , 40]])

a *b


tensor([[ 10,  40],
        [ 90, 160]])

In [21]:
# Matrix Multiplication
a@b

tensor([[ 70, 100],
        [150, 220]])

In [29]:
# Reduction operation

scores = torch.tensor([[10., 20., 30.], [5., 10., 15.]])
scores.mean()
scores.mean(dim=1)
scores.mean(dim=0)

tensor([ 7.5000, 15.0000, 22.5000])

In [32]:
# data selection

x =torch.arange(12).reshape(3, 4)

col_2 = x[:, 2]
print(f'{col_2}')

tensor([ 2,  6, 10])


In [33]:
scores = torch.tensor([[10, 20, 30], [40, 50, 60]])
best_indices = torch.argmax(scores, dim = 0)
print(f'{best_indices} for dim = 0')
best_indices = torch.argmax(scores, dim = 1)
print(f'{best_indices} for dim = 1')

tensor([1, 1, 1]) for dim = 0
tensor([2, 2]) for dim = 1


In [41]:
data = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(data)

indices_to_select = torch.tensor([[2], [0], [3]])

selected_values = torch.gather(data, dim=1, index=indices_to_select)

print(selected_values)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 3],
        [ 5],
        [12]])


In [52]:
# Building a model from scratch

# Model: simple linear regression
# y = xW + b

# first, create a fake data

# Number of data points in the input data
N = 10

# Each data point has 1 input feature and 1 output value
D_in = 1;
D_out = 1;

# Create our input data
X = torch.randn(N, D_in)

true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y_true = X @ true_W + true_b + torch.randn(N, D_out) * 0.1

# Initialize our parameters with random values
W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f'Initial Weight W = \n{W}\n')
print(f'Initial Bias b = \n{b}\n')

def model(X, W, b):
  return X @ W + b

print(model(X, W, b))

loss = ((model(X, W, b) - y_true) **2).mean()

print(loss)




Initial Weight W = 
tensor([[-0.8086]], requires_grad=True)

Initial Bias b = 
tensor([-0.4877], requires_grad=True)

tensor([[ 0.1239],
        [ 0.0584],
        [-0.9165],
        [-1.1240],
        [-0.0771],
        [-0.8751],
        [ 0.0032],
        [-1.0605],
        [-0.3112],
        [-0.3681]], grad_fn=<AddBackward0>)
tensor(4.4008, grad_fn=<MeanBackward0>)
