<a href="https://colab.research.google.com/github/ac5589/Pytorch-tutorial-Youtube/blob/main/Intro_to_CoLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [5]:
## create a list
my_list =[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [7]:
## Create numpy array
np1 = np.random.rand(3, 4)
np1

array([[0.39283085, 0.97132804, 0.13688751, 0.78766401],
       [0.27948546, 0.90032446, 0.48180672, 0.32842028],
       [0.81002837, 0.89910374, 0.69752271, 0.63822203]])

In [14]:
## Create tensor
tensor_2d = torch.randn(3, 4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.1087, -0.0109,  0.9958,  1.1911],
        [-0.2973,  0.7686, -0.7334,  1.0494],
        [ 1.1169, -0.3086, -0.4366,  2.1681]])

In [9]:
tensor_3d = torch.randn(2, 3, 4)
tensor_3d

tensor([[[ 0.7215, -0.2196, -0.5867, -0.3224],
         [ 2.2922, -0.2632, -0.1091, -1.6543],
         [-1.6841,  0.1415, -0.2665,  0.4259]],

        [[ 0.9863, -0.6591,  1.1338,  0.0556],
         [-0.8151,  0.2752,  0.3578,  0.5871],
         [ 1.3000, -0.4576,  0.7682, -1.4022]]])

In [12]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3928, 0.9713, 0.1369, 0.7877],
        [0.2795, 0.9003, 0.4818, 0.3284],
        [0.8100, 0.8991, 0.6975, 0.6382]], dtype=torch.float64)