<a href="https://colab.research.google.com/github/ac5589/Pytorch-tutorial-Youtube/blob/main/Intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [5]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
z.shape

(10,)

In [8]:
z.shape = (10, 1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [10]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
z = np.empty(4)
z

array([2.18126796e-315, 0.00000000e+000, 6.59737730e-310, 5.77764319e-317])

In [15]:
z = np.linspace(2, 10 ,5)
z.shape = (5, 1)
z

array([[ 2.],
       [ 4.],
       [ 6.],
       [ 8.],
       [10.]])

In [16]:
z = np.array([2, 3])
z

array([2, 3])

In [17]:
z.shape

(2,)

In [18]:
b_list = [1, 2, 3]
z = np.array(b_list)
z

array([1, 2, 3])

In [20]:
np.random.seed(0)
z1 = np.random.randint(10, size=6)
z1

array([5, 0, 3, 3, 7, 9])

In [24]:
z1[0:3]

array([5, 0, 3])

In [25]:
np.sin(z1)

array([-0.95892427,  0.        ,  0.14112001,  0.14112001,  0.6569866 ,
        0.41211849])

In [26]:
z1 < 3

array([False,  True, False, False, False, False])