<a href="https://colab.research.google.com/github/ac5589/Pytorch-tutorial-Youtube/blob/main/Pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
x = torch.empty(1, 2)
x

tensor([[[[2.6066e+04, 0.0000e+00],
          [0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00],
          [1.3593e-43, 0.0000e+00]]]])

In [14]:
x = torch.rand(2, 2, dtype=torch.float)
print(x)
print(x.mean(dim=1).view(2, -1))
print(x.dtype)
print(x.size())

tensor([[0.4510, 0.4989],
        [0.2439, 0.7137]])
tensor([[0.4749],
        [0.4788]])
torch.float32
torch.Size([2, 2])


In [24]:
x = torch.tensor([2, 5])
y = torch.tensor([7, 10])
print(f'x = {x}')
print(f'y = {y}')
print(x.dtype)
print((x + y).view(2, 1))
print(y.add_(x))
print(f'y = {y.view(2, 1)}')
print(f'y = {x/y}')

x = tensor([2, 5])
y = tensor([ 7, 10])
torch.int64
tensor([[ 9],
        [15]])
tensor([ 9, 15])
y = tensor([[ 9],
        [15]])
y = tensor([0.2222, 0.3333])


In [35]:
# Using the auto grad package

# Create an grad variable
x = torch.rand(1, requires_grad=True)
print(f'x = {x}')

# Perform an add operation [This is the forward pass]
y = x + 2
z = y * y * 2

# Calculate the gradient of z with respect to x
z.backward()

# The Gradient is stroed in the attribute of x called x.grad
# Here x.gad evalaute dz/dx at x
# Here dz/dx = 4*x + 8
print(f'dz/dx = 4x + 8 = {4*x + 8}')
print(f'x.grad = {x.grad}')

x = tensor([0.1343], requires_grad=True)
dz/dx = 4x + 8 = tensor([8.5372], grad_fn=<AddBackward0>)
x.grad = tensor([8.5372])


In [ ]:
# How to prevent pytorch to avoid gradient

#There are three methods to prevent tracking gradinet

# Option 1
# x.requires_grad_(False)

# Option 2
#x.detach()

# Option 3
#with torch.no_grad():


In [41]:
# GRadients should be zeros within the training loop
weight = torch.ones(4, requires_grad=True)

for epoch in range(4):
  model_output = (weight *3).sum()

  # Calculate the gradient
  model_output.backward()

  print(f'Weight grad = {weight.grad}')

  #without this step gradients will accumulate
  weight.grad.zero_()



Weight grad = tensor([3., 3., 3., 3.])
Weight grad = tensor([3., 3., 3., 3.])
Weight grad = tensor([3., 3., 3., 3.])
Weight grad = tensor([3., 3., 3., 3.])


In [44]:
# Back propagation algorithm

# Create a tensor

x = torch.tensor(1.0)

y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

# forward passs
y_hat = w*x

loss = (y_hat - y)**2

print(loss)

# Backward pass
loss.backward()

print(w.grad)


tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [56]:
# Manual training

import numpy as np

# Linear regression f = w * x

X = np.array([1, 2, 3, 4], dtype=np.float32)

Y = np.array([2, 4, 6, 8], dtype = np.float32)

w = 0.0

# Model prediction

def forward(x):
  return w*x

def loss(y, y_predicted):
  return ((y_predicted -y)**2).mean()

def gradient(x, y, y_predicted):
  return np.dot(2*x, y_predicted-y).mean()

print(f'Prediction before training: f(5) = {forward(5)}')

# Training

learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
  y_pred = forward(X)

  l = loss(Y, y_pred)

  dw = gradient(X, Y, y_pred)

  w -= learning_rate * dw

  if epoch%1==0:
    print(f'epoch = {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5)}')





Prediction before training: f(5) = 0.0
epoch = 1: w = 1.200, loss = 30.00000000
epoch = 2: w = 1.680, loss = 4.80000067
epoch = 3: w = 1.872, loss = 0.76800019
epoch = 4: w = 1.949, loss = 0.12288000
epoch = 5: w = 1.980, loss = 0.01966083
epoch = 6: w = 1.992, loss = 0.00314574
epoch = 7: w = 1.997, loss = 0.00050332
epoch = 8: w = 1.999, loss = 0.00008053
epoch = 9: w = 1.999, loss = 0.00001288
epoch = 10: w = 2.000, loss = 0.00000206
epoch = 11: w = 2.000, loss = 0.00000033
epoch = 12: w = 2.000, loss = 0.00000005
epoch = 13: w = 2.000, loss = 0.00000001
epoch = 14: w = 2.000, loss = 0.00000000
epoch = 15: w = 2.000, loss = 0.00000000
epoch = 16: w = 2.000, loss = 0.00000000
epoch = 17: w = 2.000, loss = 0.00000000
epoch = 18: w = 2.000, loss = 0.00000000
epoch = 19: w = 2.000, loss = 0.00000000
epoch = 20: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.0


In [64]:
# Manual training
# Use gradient functon from pytorch

#import numpy as np

# Linear regression f = w * x

#X = np.array([1, 2, 3, 4], dtype=np.float32)
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)

#Y = np.array([2, 4, 6, 8], dtype = np.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

#w = 0.0
w = torch.tensor([0], dtype=torch.float32, requires_grad=True)

# Model prediction

def forward(x):
  return w*x

def loss(y, y_predicted):
  return ((y_predicted -y)**2).mean()

print(f'Prediction before training: f(5) = {forward(5)}')

# Training

learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
  y_pred = forward(X)

  l = loss(Y, y_pred)

  #dw = gradient(X, Y, y_pred)
  l.backward()

  with torch.no_grad():
    #w -= learning_rate * dw
    w -= learning_rate * w.grad

  w.grad.zero_()

  if epoch%10==0:
    print(f'epoch = {epoch+1}: w = {w.item():.3f}, loss = {l.item():.8f}')

print(f'Prediction after training: f(5) = {forward(5)}')

Prediction before training: f(5) = tensor([0.], grad_fn=<MulBackward0>)
epoch = 1: w = 0.300, loss = 30.00000000
epoch = 11: w = 1.665, loss = 1.16278565
epoch = 21: w = 1.934, loss = 0.04506890
epoch = 31: w = 1.987, loss = 0.00174685
epoch = 41: w = 1.997, loss = 0.00006770
epoch = 51: w = 1.999, loss = 0.00000262
epoch = 61: w = 2.000, loss = 0.00000010
epoch = 71: w = 2.000, loss = 0.00000000
epoch = 81: w = 2.000, loss = 0.00000000
epoch = 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = tensor([10.0000], grad_fn=<MulBackward0>)


In [80]:
#Complete operation using pytorch package

import torch.nn as nn

# Linear regression f = w * x

X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)
X_test = torch.tensor([[5]], dtype=torch.float32)
n_sample, n_features = X.shape
print(n_sample, n_features)

input_size = n_features
output_size = n_features

model = nn.Linear(in_features=input_size, out_features=output_size)

class LinearRegression(nn.Module):
  def __init__(self, input_dim, ouput_dim):
    super(self)

print(f'Prediction before training: f(5) = {model(X_test).item()}')

# Training

learning_rate = 0.01
n_iters = 500

loss = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr= learning_rate)

for epoch in range(n_iters):
  y_pred = model(X)

  l = loss(Y, y_pred)

  #dw = gradient(X, Y, y_pred)
  l.backward()

  optimizer.step()

  optimizer.zero_grad()

  if epoch%10==0:
    [w, b] = model.parameters()
    print(f'epoch = {epoch+1}: w = {w[0][0].item():.3f}, loss = {l.item():.8f}')

print(f'Prediction after training: f(5) = {model(X_test).item()}')


4 1
Prediction before training: f(5) = 3.512997627258301
epoch = 1: w = 0.814, loss = 14.01943398
epoch = 11: w = 0.914, loss = 11.41578865
epoch = 21: w = 1.011, loss = 9.12295151
epoch = 31: w = 1.105, loss = 7.15880346
epoch = 41: w = 1.194, loss = 5.51852131
epoch = 51: w = 1.276, loss = 4.18000078
epoch = 61: w = 1.353, loss = 3.11099243
epoch = 71: w = 1.423, loss = 2.27489161
epoch = 81: w = 1.485, loss = 1.63454962
epoch = 91: w = 1.542, loss = 1.15458095
epoch = 101: w = 1.591, loss = 0.80273163
epoch = 111: w = 1.634, loss = 0.55065733
epoch = 121: w = 1.672, loss = 0.37427676
epoch = 131: w = 1.704, loss = 0.25379443
epoch = 141: w = 1.730, loss = 0.17347370
epoch = 151: w = 1.753, loss = 0.12120819
epoch = 161: w = 1.771, loss = 0.08799136
epoch = 171: w = 1.786, loss = 0.06733918
epoch = 181: w = 1.798, loss = 0.05473729
epoch = 191: w = 1.808, loss = 0.04714270
epoch = 201: w = 1.816, loss = 0.04257009
epoch = 211: w = 1.823, loss = 0.03976673
epoch = 221: w = 1.828, loss