<a href="https://colab.research.google.com/github/ac5589/Pytorch-tutorial-Youtube/blob/main/Tensor_Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch as np

In [3]:
# Initialize the tensor
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [4]:
# Addition
tensor_add = tensor_a + tensor_b
tensor_add

tensor([ 6,  8, 10, 12])

In [8]:
# Addition Long hand
tensor_add1 = torch.add(tensor_a, tensor_b)
tensor_add1

tensor([ 6,  8, 10, 12])

In [9]:
# subtract
tensor_subtract = tensor_a - tensor_b
tensor_subtract

tensor([-4, -4, -4, -4])

In [10]:
# Sub function
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [12]:
# Multiplication
tensor_mult = tensor_a * tensor_b
tensor_mult

tensor([ 5, 12, 21, 32])

In [13]:
# Multiplicaton Long hand
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [14]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
# Division long hand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
# Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [18]:
# Modulus Long hand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [19]:
# Exponents
torch.pow(tensor_b, tensor_a)

tensor([   5,   36,  343, 4096])

In [20]:
# Another way to write long hand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [21]:
# Reassignment
tensor_a = tensor_a + tensor_b
tensor_a

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a.add(tensor_b)

tensor([11, 14, 17, 20])

In [24]:
tensor_a

tensor([ 6,  8, 10, 12])

In [25]:
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [26]:
tensor_a

tensor([11, 14, 17, 20])