<a href="https://colab.research.google.com/github/ac5589/Pytorch-tutorial-Youtube/blob/main/Tensor_Operations_Reshape_and_Slice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
# create a tensor
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reshape and view the tensor
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# reshpae if we dont know the number of items
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch3 = torch.arange(10)
my_torch3 = my_torch3.view(2, 5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
# reshape and view does update the final tensor
my_torch5 = torch.arange(10)
my_torch6 = my_torch5.reshape(2, 5)
my_torch6
my_torch5[1] = 414
my_torch6

tensor([[  0, 414,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [18]:
# Grab a specifc item
my_torch7 = torch.arange(10)
my_torch7[7]

tensor(7)

In [20]:
# Grab a column
my_torch8 = torch.arange(10)
my_torch8 = my_torch8.reshape(5, 2)
my_torch8[:, 1]

tensor([1, 3, 5, 7, 9])

In [21]:
# Return a column
my_torch8 = torch.arange(10)
my_torch8 = my_torch8.reshape(5, 2)
my_torch8[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])